### ISSUE TITLE
Route for HMVC structure

### ISSUE THREAD

**Issue by lsdralcanar** [kenjis/ci4-attribute-routes#10]
Hi,

Good day! Can we use this for HMVC structure?

Thank you

**Comment by kenjis** [comment]
It should work. Try it.

**Comment by lsdralcanar** [comment]
Thanks. It already worked. 

I followed this link for hmvc tutorial: 

https://onlinewebtutorblog.com/codeigniter-4-hmvc-programming/

Thank you.
