### ISSUE TITLE
Abstract Controllers

### ISSUE THREAD

**Issue by KrisDriv** [kenjis/ci4-attribute-routes#6]
I have created an abstract CRUD controller which has all the routes defined for typical CRUD use case.

However the attributes are read and declaring class that is used is an abstract one. Defined routes are now pointing to a class that can not be constructor. Could you add the possibility for it use the child class instead?

**Comment by kenjis** [comment]
I don't get what you say. Can you show sample code?

**Comment by KrisDriv** [comment]
```php
<?php

namespace App\Controllers;

use App\Controllers\Traits\ModelResolverTrait;
use App\Models\MachineTypeModel;
use App\Models\Traits\SafeOperationsTrait;
use CodeIgniter\Exceptions\PageNotFoundException;
use CodeIgniter\HTTP\RedirectResponse;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use Kenjis\CI4\AttributeRoutes\Route;
use Kenjis\CI4\AttributeRoutes\RouteGroup;
use ReflectionClass;
use ReflectionException;

abstract class CrudController extends BaseController
{

    #[Route('/', methods: ['get'])]
    public function index(): string
    {
        
    }

    #[Route('edit/(:num)', ['get'])]
    public function edit(int $id): string
    {
        
    }

    #[Route('create', ['get'])]
    public function create(): string
    {
       
    }

    #[Route('store', ['post'])]
    public function store(): RedirectResponse
    {
        
    }

    #[Route('update/(:num)', ['post'])]
    public function update(int $id): RedirectResponse
    {

    }

    #[Route('delete/(:num)', ['get'])]
    public function delete(int $id): RedirectResponse
    {
           
    }
}
```

And so the child is

```php
<?php

namespace App\Controllers;

use Kenjis\CI4\AttributeRoutes\RouteGroup;

#[RouteGroup('machine-types')]
class MachineTypeController extends CrudController
{

}
```

I expect the MachineTypeController to "include" routes & methods from the parent.

**Comment by KrisDriv** [comment]
Instead it uses CrudController itself and registers routes to it.

**Comment by KrisDriv** [comment]
ReflectionClass does read inhereted methods. The issue was that it was using the class that declared the method. It didn't work for my use-case where the class which declared it was an abstract one.

I forked your repo and commited the changes to it. Not sure if I didn't break anything else or if it works in the intended ways.
